import type { MenuItem } from "@/types";

export const MENU_ITEMS: MenuItem[] = [
  // ── Starters ────────────────────────────────────────────────────
  {
    id: "samosa",
    name: "Crispy Samosa",
    description: "Hand-crimped pastry filled with spiced potato and peas, fried until golden. Served with mint chutney and tamarind.",
    price: 8,
    category: "starters",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    veg: true,
    spice: 1,
    popular: true,
  },
  {
    id: "paneer-tikka",
    name: "Paneer Tikka",
    description: "Cottage cheese cubes marinated in yoghurt and spices, charred in a tandoor with bell peppers and onion.",
    price: 14,
    category: "starters",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7",
    veg: true,
    spice: 1,
    popular: true,
    tags: ["tandoor"],
  },
  {
    id: "seekh-kebab",
    name: "Seekh Kebab",
    description: "Minced lamb blended with ginger, green chilli and aromatic herbs, pressed onto skewers and grilled over charcoal.",
    price: 15,
    category: "starters",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8",
    veg: false,
    spice: 2,
    tags: ["tandoor", "grilled"],
  },
  {
    id: "onion-bhaji",
    name: "Onion Bhaji",
    description: "Shredded onion, fresh coriander and chilli bound in a chickpea batter and deep-fried to crisp fritters.",
    price: 9,
    category: "starters",
    image: "https://images.unsplash.com/photo-1601050690294-397f3c324515",
    veg: true,
    spice: 1,
  },

  // ── Mains ───────────────────────────────────────────────────────
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    description: "Slow-cooked chicken in a silky tomato-cream sauce with cardamom, fenugreek and a touch of smoke. Our most requested dish.",
    price: 18,
    category: "mains",
    image: "https://images.unsplash.com/photo-1742599361498-79824d24e355",
    veg: false,
    spice: 1,
    popular: true,
    tags: ["bestseller"],
  },
  {
    id: "chicken-tikka-masala",
    name: "Chicken Tikka Masala",
    description: "Charcoal-kissed chicken tikka finished in a bold onion-tomato masala with cream and roasted cumin.",
    price: 19,
    category: "mains",
    image: "https://images.unsplash.com/photo-1666001120694-3ebe8fd207be",
    veg: false,
    spice: 2,
    popular: true,
  },
  {
    id: "lamb-rogan-josh",
    name: "Lamb Rogan Josh",
    description: "Slow-braised Kashmiri lamb in a deep, aromatic gravy built on whole spices, dried chillies and Kashmiri saffron.",
    price: 22,
    category: "mains",
    image: "https://images.unsplash.com/photo-1690403160225-3db8cc8babd5",
    veg: false,
    spice: 2,
    tags: ["Kashmiri"],
  },
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    description: "Black lentils and kidney beans simmered overnight on a slow flame, finished with butter and single cream.",
    price: 15,
    category: "mains",
    image: "https://images.unsplash.com/photo-1690401767645-595de0e0e5f8",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    description: "Garden-fresh spinach blanched and puréed with garlic and ginger, folded around pillowy cottage cheese cubes.",
    price: 16,
    category: "mains",
    image: "https://images.unsplash.com/photo-1690401769082-5f475f87fb22",
    veg: true,
    spice: 0,
  },
  {
    id: "prawn-masala",
    name: "Prawn Masala",
    description: "Tiger prawns sautéed in a coastal masala of coconut, curry leaf and Konkan-style red chilli paste.",
    price: 24,
    category: "mains",
    image: "https://images.unsplash.com/photo-1689314609988-2d9a0a5bcf2d",
    veg: false,
    spice: 3,
    tags: ["coastal"],
  },

  // ── Biryani & Rice ──────────────────────────────────────────────
  {
    id: "chicken-biryani",
    name: "Chicken Dum Biryani",
    description: "Aged Basmati layered with slow-cooked chicken and sealed with dough, baked on a low flame until the rice absorbs every aroma.",
    price: 20,
    category: "biryani",
    image: "https://images.unsplash.com/photo-1559528896-c5310744cce8",
    veg: false,
    spice: 2,
    popular: true,
    tags: ["dum-cooked"],
  },
  {
    id: "veg-biryani",
    name: "Vegetable Dum Biryani",
    description: "Seasonal vegetables and paneer layered with saffron rice, sealed and baked until the grains bloom.",
    price: 16,
    category: "biryani",
    image: "https://images.unsplash.com/photo-1572099107898-46f22b3af4f9",
    veg: true,
    spice: 1,
  },
  {
    id: "lamb-biryani",
    name: "Lamb Dum Biryani",
    description: "Bone-in lamb slow-cooked with whole spices, layered with golden-fried onion and long-grain Basmati.",
    price: 24,
    category: "biryani",
    image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db",
    veg: false,
    spice: 2,
    popular: true,
  },

  // ── Breads ──────────────────────────────────────────────────────
  {
    id: "garlic-naan",
    name: "Garlic Naan",
    description: "Leavened dough blisterred in the tandoor, brushed with garlic butter and fresh coriander while hot.",
    price: 4,
    category: "breads",
    image: "https://images.unsplash.com/photo-1622715395488-71045e2a4990",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "paratha",
    name: "Whole Wheat Paratha",
    description: "Flaky layered flatbread cooked on a griddle with a brush of ghee. Pairs well with any curry.",
    price: 5,
    category: "breads",
    image: "https://images.unsplash.com/photo-1622715395486-08183374570a",
    veg: true,
    spice: 0,
  },
  {
    id: "peshwari-naan",
    name: "Peshwari Naan",
    description: "Sweet naan stuffed with coconut, almond and sultanas — an irresistible contrast to rich curries.",
    price: 5,
    category: "breads",
    image: "https://images.unsplash.com/photo-1589301773859-bb024d3ad558",
    veg: true,
    spice: 0,
  },

  // ── Desserts ────────────────────────────────────────────────────
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    description: "Soft milk-solid dumplings soaked in rose and cardamom syrup, served warm with a scoop of malai kulfi.",
    price: 7,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1593701461250-d7b22dfd3a77",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "kheer",
    name: "Rice Kheer",
    description: "Slow-reduced rice pudding flavoured with green cardamom, saffron strands and topped with toasted pistachios.",
    price: 8,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1666190092159-3171cf0fbb12",
    veg: true,
    spice: 0,
  },
  {
    id: "kulfi",
    name: "Pistachio Kulfi",
    description: "Dense, hand-churned Indian ice cream set in conical moulds with crushed pistachio and rose water.",
    price: 7,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1646578515903-67873a5398f9",
    veg: true,
    spice: 0,
  },

  // ── Drinks ──────────────────────────────────────────────────────
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    description: "Alphonso mango blended with thick yoghurt and a pinch of cardamom. Cooling, creamy, unmistakably Indian.",
    price: 6,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "masala-chai",
    name: "Masala Chai",
    description: "Assam tea simmered with ginger, cardamom, cinnamon and cloves, poured over steamed whole milk.",
    price: 4,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1683533698664-12ee473e8c9d",
    veg: true,
    spice: 1,
  },
  {
    id: "fresh-lime-soda",
    name: "Fresh Lime Soda",
    description: "Freshly squeezed lime, black salt, cumin water and chilled soda — sweet, salty or mixed.",
    price: 5,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1764403713624-44a80917851b",
    veg: true,
    spice: 0,
  },
];

export const CATEGORIES: { id: string; label: string; emoji: string }[] = [
  { id: "all",      label: "All",           emoji: "🍽️" },
  { id: "starters", label: "Starters",      emoji: "🥟" },
  { id: "mains",    label: "Mains",         emoji: "🍛" },
  { id: "biryani",  label: "Biryani",       emoji: "🍚" },
  { id: "breads",   label: "Breads",        emoji: "🫓" },
  { id: "desserts", label: "Desserts",      emoji: "🍮" },
  { id: "drinks",   label: "Drinks",        emoji: "🥤" },
];
