import type { MenuItem } from "@/types";

export const MENU_ITEMS: MenuItem[] = [
  // ── Starters ────────────────────────────────────────────────────
  {
    id: "samosa",
    name: "Crispy Samosa",
    description: "Hand-crimped pastry filled with spiced potato and peas, fried until golden. Served with mint chutney and tamarind.",
    price: 8,
    category: "starters",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950",
    veg: true,
    spice: 1,
    popular: true,
  },
  {
    id: "paneer-tikka",
    name: "Paneer Tikka",
    description: "Cottage cheese cubes marinated in yoghurt and spices, charred in a tandoor with bell peppers and onion.",
    price: 14,
    category: "starters",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8",
    veg: true,
    spice: 1,
    popular: true,
    tags: ["tandoor"],
  },
  {
    id: "seekh-kebab",
    name: "Seekh Kebab",
    description: "Minced lamb blended with ginger, green chilli and aromatic herbs, pressed onto skewers and grilled over charcoal.",
    price: 15,
    category: "starters",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0",
    veg: false,
    spice: 2,
    tags: ["tandoor", "grilled"],
  },
  {
    id: "onion-bhaji",
    name: "Onion Bhaji",
    description: "Shredded onion, fresh coriander and chilli bound in a chickpea batter and deep-fried to crisp fritters.",
    price: 9,
    category: "starters",
    image: "https://images.unsplash.com/photo-1601050690294-397f3c324515",
    veg: true,
    spice: 1,
  },

  // ── Mains ───────────────────────────────────────────────────────
  {
    id: "butter-chicken",
    name: "Butter Chicken",
    description: "Slow-cooked chicken in a silky tomato-cream sauce with cardamom, fenugreek and a touch of smoke. Our most requested dish.",
    price: 18,
    category: "mains",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641",
    veg: false,
    spice: 1,
    popular: true,
    tags: ["bestseller"],
  },
  {
    id: "chicken-tikka-masala",
    name: "Chicken Tikka Masala",
    description: "Charcoal-kissed chicken tikka finished in a bold onion-tomato masala with cream and roasted cumin.",
    price: 19,
    category: "mains",
    image: "https://images.unsplash.com/photo-1604579905004-53e58d6b87c9",
    veg: false,
    spice: 2,
    popular: true,
  },
  {
    id: "lamb-rogan-josh",
    name: "Lamb Rogan Josh",
    description: "Slow-braised Kashmiri lamb in a deep, aromatic gravy built on whole spices, dried chillies and Kashmiri saffron.",
    price: 22,
    category: "mains",
    image: "https://images.unsplash.com/photo-1545247181-516773cae754",
    veg: false,
    spice: 2,
    tags: ["Kashmiri"],
  },
  {
    id: "dal-makhani",
    name: "Dal Makhani",
    description: "Black lentils and kidney beans simmered overnight on a slow flame, finished with butter and single cream.",
    price: 15,
    category: "mains",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "palak-paneer",
    name: "Palak Paneer",
    description: "Garden-fresh spinach blanched and puréed with garlic and ginger, folded around pillowy cottage cheese cubes.",
    price: 16,
    category: "mains",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe",
    veg: true,
    spice: 0,
  },
  {
    id: "prawn-masala",
    name: "Prawn Masala",
    description: "Tiger prawns sautéed in a coastal masala of coconut, curry leaf and Konkan-style red chilli paste.",
    price: 24,
    category: "mains",
    image: "https://images.unsplash.com/photo-1625943553852-781c6dd46faa",
    veg: false,
    spice: 3,
    tags: ["coastal"],
  },

  // ── Biryani & Rice ──────────────────────────────────────────────
  {
    id: "chicken-biryani",
    name: "Chicken Dum Biryani",
    description: "Aged Basmati layered with slow-cooked chicken and sealed with dough, baked on a low flame until the rice absorbs every aroma.",
    price: 20,
    category: "biryani",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8",
    veg: false,
    spice: 2,
    popular: true,
    tags: ["dum-cooked"],
  },
  {
    id: "veg-biryani",
    name: "Vegetable Dum Biryani",
    description: "Seasonal vegetables and paneer layered with saffron rice, sealed and baked until the grains bloom.",
    price: 16,
    category: "biryani",
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b",
    veg: true,
    spice: 1,
  },
  {
    id: "lamb-biryani",
    name: "Lamb Dum Biryani",
    description: "Bone-in lamb slow-cooked with whole spices, layered with golden-fried onion and long-grain Basmati.",
    price: 24,
    category: "biryani",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0",
    veg: false,
    spice: 2,
    popular: true,
  },

  // ── Breads ──────────────────────────────────────────────────────
  {
    id: "garlic-naan",
    name: "Garlic Naan",
    description: "Leavened dough blistered in the tandoor, brushed with garlic butter and fresh coriander while hot.",
    price: 4,
    category: "breads",
    image: "https://images.unsplash.com/photo-1604868189265-219ba0703b26",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "paratha",
    name: "Whole Wheat Paratha",
    description: "Flaky layered flatbread cooked on a griddle with a brush of ghee. Pairs well with any curry.",
    price: 5,
    category: "breads",
    image: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a",
    veg: true,
    spice: 0,
  },
  {
    id: "peshwari-naan",
    name: "Peshwari Naan",
    description: "Sweet naan stuffed with coconut, almond and sultanas — an irresistible contrast to rich curries.",
    price: 5,
    category: "breads",
    image: "https://images.unsplash.com/photo-1589301773859-bb024d3ad558",
    veg: true,
    spice: 0,
  },

  // ── Desserts ────────────────────────────────────────────────────
  {
    id: "gulab-jamun",
    name: "Gulab Jamun",
    description: "Soft milk-solid dumplings soaked in rose and cardamom syrup, served warm with a scoop of malai kulfi.",
    price: 7,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1593701461250-d7b22dfd3a77",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "kheer",
    name: "Rice Kheer",
    description: "Slow-reduced rice pudding flavoured with green cardamom, saffron strands and topped with toasted pistachios.",
    price: 8,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1615832494873-b0c52d519696",
    veg: true,
    spice: 0,
  },
  {
    id: "kulfi",
    name: "Pistachio Kulfi",
    description: "Dense, hand-churned Indian ice cream set in conical moulds with crushed pistachio and rose water.",
    price: 7,
    category: "desserts",
    image: "https://images.unsplash.com/photo-1501443762994-82bd5dace89a",
    veg: true,
    spice: 0,
  },

  // ── Drinks ──────────────────────────────────────────────────────
  {
    id: "mango-lassi",
    name: "Mango Lassi",
    description: "Alphonso mango blended with thick yoghurt and a pinch of cardamom. Cooling, creamy, unmistakably Indian.",
    price: 6,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1527661591475-527312dd65f5",
    veg: true,
    spice: 0,
    popular: true,
  },
  {
    id: "masala-chai",
    name: "Masala Chai",
    description: "Assam tea simmered with ginger, cardamom, cinnamon and cloves, poured over steamed whole milk.",
    price: 4,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1561336313-0bd5e0b27ec8",
    veg: true,
    spice: 1,
  },
  {
    id: "fresh-lime-soda",
    name: "Fresh Lime Soda",
    description: "Freshly squeezed lime, black salt, cumin water and chilled soda — sweet, salty or mixed.",
    price: 5,
    category: "drinks",
    image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859",
    veg: true,
    spice: 0,
  },
];

export const CATEGORIES: { id: string; label: string; emoji: string }[] = [
  { id: "all",      label: "All",      emoji: "🍽️" },
  { id: "starters", label: "Starters", emoji: "🥟" },
  { id: "mains",    label: "Mains",    emoji: "🍛" },
  { id: "biryani",  label: "Biryani",  emoji: "🍚" },
  { id: "breads",   label: "Breads",   emoji: "🫓" },
  { id: "desserts", label: "Desserts", emoji: "🍮" },
  { id: "drinks",   label: "Drinks",   emoji: "🥤" },
];
